spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=mydb;encrypt=false;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
    
debezium:
  connector:
    name: sqlserver-connector
    class: io.debezium.connector.sqlserver.SqlServerConnector
    tasks.max: 1
    database.server.name: dbserver1
    database.hostname: localhost
    database.port: 1433
    database.user: sa
    database.password: YourStrong!Passw0rd
    database.names: mydb
    topic.prefix: dbserver1
    database.history.kafka.bootstrap.servers: localhost:9092
    database.history.kafka.topic: dbhistory.mydb
    database.history.producer.bootstrap.servers: localhost:9092
    database.history.producer.topic: dbhistory.mydb


