spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=mydb;encrypt=false;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
    
debezium:
  database:
    names: ADMR_00_00
    table:
      include-list: dbo.AreaConsoles
  topic-prefix: DMR.SYM
  offset:
    storage:
      jdbc:
        offset-table-name: dmr_sym_debezium_offsets
        offset-table-ddl: CREATE TABLE %s
          (
            id VARCHAR(36) NOT NULL,
            offset_key VARCHAR(1255),
            offset_val VARCHAR(1255),
            record_insert_ts DATETIME NOT NULL,
            record_insert_seq INTEGER NOT NULL,
          )
        schema-history-table-name: dmr_sym_schema_history
        schema-history-table-ddl: CREATE TABLE %s
          (
          id VARCHAR(36) NOT NULL,
          history_data VARCHAR(MAX),
          history_data_seq INTEGER,
          record_insert_ts DATETIME NOT NULL,
          record_insert_seq INTEGER NOT NULL,
          )
        schema-history-table-exits: SELECT TOP 1 * FROM %s
        
        
  connector:
    name: sqlserver-connector
    class: io.debezium.connector.sqlserver.SqlServerConnector
    tasks.max: 1
    database.server.name: dbserver1
    database.hostname: localhost
    database.port: 1433
    database.user: sa
    database.password: YourStrong!Passw0rd
    database.names: mydb
    topic.prefix: dbserver1
    database.history.kafka.bootstrap.servers: localhost:9092
    database.history.kafka.topic: dbhistory.mydb
    database.history.producer.bootstrap.servers: localhost:9092
    database.history.producer.topic: dbhistory.mydb


