spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=mydb;encrypt=false;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
    

debezium:
  name: "embedded-sqlserver"
  connector:
    class: "io.debezium.connector.sqlserver.SqlServerConnector"
  database:
    hostname: "localhost"
    port: 1433
    user: "sa"
    password: "YourStrong!Passw0rd"
    dbname: "mydb"
    server_name: "sqlserver_cdc"
    snapshot_mode: "initial"
  include:
    schema_changes: true
    tables: "dbo.users,dbo.orders"

