version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - ./db-init.sql:/db-init.sql
    
    command: >
      /bin/bash -c "
      (/opt/mssql/bin/sqlservr &) &&
      sleep 30 &&
      opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -d master -C -i /db-init.sql &&
      
      tail -f /dev/null"
    
